checkpoint_dir: checkpoints
config_setter_name:
- volume_level_config_setter
- set_input_channels
data_params:
  channel_reg_ex: null
  data_root: data
  electrode_file_path: processed_data/all_subject_sig.csv
  embedding_layer: null
  embedding_pca_dim: null
  embedding_type: gpt-2xl
  per_subject_electrodes:
    1:
    - G14
    - G16
    - G20
    - G21
    - G22
    - G23
    - G26
    - G27
    - G28
    - G41
    - G49
    - G55
    - G62
    - PT1
    - MT4
    3:
    - LGA10
    - LGA18
    - LGA27
    - LGA32
    - LGA36
    - LGA37
    - LGA38
    - LGA39
    - LGA4
    - LGA44
    - LGA46
    - LGA47
    - LGA9
    - LGB108
    - LGB112
    - LGB113
    - LGB114
    - LGB116
    - LGB117
    - LGB119
    - LGB120
    - LGB121
    - LGB122
    - LGB126
    - LGB66
    - LGB71
    - LGB74
    - LGB75
    - LGB78
    - LGB79
    - LGB80
    - LGB82
    - LGB85
    - LGB86
    - LGB87
    - LGB88
    - LGB95
    - LOF4
    - RO7
    - RPT1
    - RPT2
    - RPT3
    - RPT4
    4:
    - LSF12
    - LST10
    - LPT2
    - LPT1
    - LIF3
    - LST1
    - LST2
    - RIF4
    - RIF12
    - RST4
    - RST5
    - LDII7
    - LDII8
    - LDII9
    - LDSI9
    - LDSI10
    - LST7
    - LST8
    5:
    - GA48
    - GA64
    - GA44
    - GA45
    - GA47
    - GA14
    - GA23
    - GA41
    6:
    - dMF5
    - dPI5
    - G101
    - G102
    - G103
    - G104
    - G108
    - G110
    - G111
    - G113
    - G117
    - G118
    - G119
    - G120
    - G121
    - G124
    - G125
    - G128
    - G15
    - G22
    - G23
    - G24
    - G30
    - G31
    - G34
    - G35
    - G37
    - G42
    - G43
    - G44
    - G45
    - G53
    - G54
    - G55
    - G56
    - G61
    - G63
    - G64
    - G7
    - G75
    7:
    - G3
    - G11
    - G64
    - G46
    - G47
    - G44
    - G45
    - G52
    - G53
    - G54
    - G19
    - G10
    8:
    - G25
    - G33
    - AT1
    - DPMT7
    - G15
    - G31
    - G32
    - G20
    - G21
    - G23
    - G24
    - G34
    - DAI3
    - DAI4
    - DPI3
    - DPMT8
    9:
    - AF6
    - AIT3
    - DPI2
    - DPI3
    - G10
    - G12
    - G15
    - G16
    - G17
    - G18
    - G19
    - G20
    - G26
    - G27
    - G5
    - G56
    - G77
    - G79
    - G83
    - G84
    - G86
    - G87
    - G88
    - G92
    - G93
    - G94
    - G95
    - G96
    - O4
    - O6
    - SF2
  preprocessing_fn_name:
  - window_rms
  preprocessor_params: null
  subject_ids:
  - 1
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  task_params:
    allow_resample_audio: true
    audio_path: stimuli/podcast.wav
    butter_order: 4
    cutoff_hz: 8.0
    hop_size: 25.0
    target_sr: 512
    window_size: 200.0
    zero_phase: true
  window_width: 0.2
  word_column: null
format_fields: null
model_constructor_name: torch_ridge_model
model_params:
  bias: true
  device: cuda
  embedding_dim: 1
  input_channels: 183
output_dir: results
task_name: volume_level_decoding_task
tensorboard_dir: event_logs
training_params:
  batch_size: 64
  cudnn_deterministic: false
  early_stopping_metric: r2
  early_stopping_patience: 10
  epochs: 50
  fold_type: sequential_folds
  grad_accumulation_steps: 1
  lag: null
  lag_step_size: 200
  learning_rate: 0.05
  linear_regression_baseline: false
  logistic_regression_baseline: false
  loss_name: null
  loss_weights:
  - 1.0
  losses:
  - mse
  max_lag: 1000
  metrics:
  - r2
  - corr
  min_lag: -1000
  min_test_freq_auc: -1
  min_train_freq_auc: 5
  n_folds: 10
  normalize_targets: false
  random_seed: 42
  ridge_alpha: 1.0
  ridge_regression_baseline: false
  shuffle_targets: false
  smaller_is_better: false
  tensorboard_logging: true
  top_k_thresholds:
  - 1
  - 5
  - 10
  visualize_fold_distribution: false
  weight_decay: 0.001
trial_name: volume_level_torch_ridge
